name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - name: Build Tokens
        working-directory: ./packages/tokens
        run: npm run build

      - name: Build React
        working-directory: ./packages/react
        run: npm run build

      - name: Build Storybook
        working-directory: ./packages/docs
        run: npm run build || (echo "Storybook build falhou" && exit 1)

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
      
      - name: Verificar saída do build
        run: ls -R
